#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

source ${OPENSHIFT_DATA_DIR}.env
cd $OPENSHIFT_REPO_DIR
mrt install

if [ -z "$(ps -ef | grep node | grep -v grep)" ]
then
    nohup meteor > ${OPENSHIFT_DIY_LOG_DIR}server.log 2>&1 &
fi
